### ISSUE TITLE
Got fatal error on Client listener socket: Connection reset by peer

### ISSUE THREAD

**Issue by Tinywan** [revmischa/rtsp-server#21] opened 2017-02-14 02:33 UTC
Failed to find client RTP start port in SETUP request
Got fatal error on Client listener socket: Connection reset by peer
Failed to find client RTP start port in SETUP request

**Comment by revmischa** [comment] 2017-02-14 21:56
dupe of #20

**Closed by revmischa** 2017-02-14 21:56 UTC
